### ISSUE TITLE
Multi-level menu support

### ISSUE THREAD

**Issue by marcingaleza** [teamscops/bulmapress#14] opened 2018-02-06 13:14 UTC
Hi,

I have a question if that theme supports multi-level menu in the header navigation. I'm trying to build something based on this great theme, but I found all my menu items are at the same level (root) even if Menu is constructed correctly (works with other themes).

**Comment by eeegor** [comment] 2018-02-13 15:49
@marcingaleza thanks for your kind words. Sorry, at this point the menu is one-level support only. @raygervais might be a good feature to implement?

**Comment by marcingaleza** [comment] 2018-02-13 16:11
That would be a great extension!

**Comment by senlin** [comment] 2018-03-06 18:44
I need this also for a site I am working on and instead of messing with the custom walker, I think it is probably easiest to remove the custom walker entirely and add a filter using [nav_menu_css_class()](https://codex.wordpress.org/Plugin_API/Filter_Reference/nav_menu_css_class)

**Comment by eeegor** [comment] 2019-03-01 21:47
@senlin thanks for the suggestion, would you be willing to submit an MR?

**Comment by eeegor** [comment] 2019-03-01 22:02
Closing for now as it's a duplicate of #3

**Closed by eeegor** 2019-03-01 22:02 UTC
Labels: help wanted

**Comment by senlin** [comment] 2019-03-02 16:49
@eeegor - lost interest in this

**Comment by eeegor** [comment] 2019-03-02 19:56
@senlin basic multi-level support has been merged in #21, bug reports are welcomed 😃
